version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: pronto_postgres_db
    environment:
      POSTGRES_DB: company_intelligence
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: pronto_django_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-company-intelligence-key-998877
      - USE_POSTGRES=True
      - DB_NAME=company_intelligence
      - DB_USER=postgres
      - DB_PASSWORD=postgrespassword
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data:
