# Generated by Django 5.2.17 on 2026-08-09 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('official_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('website', models.URLField(max_length=500)),
                ('logo_url', models.CharField(max_length=500)),
                ('founder', models.CharField(max_length=255)),
                ('founded_year', models.IntegerField()),
                ('headquarters', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('business_model', models.TextField()),
                ('target_customers', models.TextField()),
                ('services', models.JSONField(default=list)),
                ('cities', models.JSONField(default=list)),
                ('expansion_summary', models.TextField(blank=True)),
                ('last_researched_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_funding_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_funding_formatted', models.CharField(max_length=100)),
                ('latest_round', models.CharField(max_length=100)),
                ('latest_round_date', models.CharField(max_length=100)),
                ('valuation_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valuation_formatted', models.CharField(max_length=100)),
                ('revenue_formatted', models.CharField(default='Not Publicly Available', max_length=100)),
                ('employee_count_formatted', models.CharField(max_length=100)),
                ('active_professionals_formatted', models.CharField(blank=True, max_length=255)),
                ('daily_bookings_formatted', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('as_of_date', models.CharField(max_length=100)),
                ('source_name', models.CharField(max_length=255)),
                ('source_url', models.URLField(max_length=500)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='FundingRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_type', models.CharField(max_length=100)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_formatted', models.CharField(max_length=100)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('date', models.CharField(max_length=100)),
                ('valuation_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valuation_formatted', models.CharField(blank=True, max_length=100, null=True)),
                ('investors', models.JSONField(default=list)),
                ('source_name', models.CharField(max_length=255)),
                ('source_url', models.URLField(max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_rounds', to='companies.company')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GrowthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=255)),
                ('metric_value', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=100)),
                ('source_name', models.CharField(max_length=255)),
                ('source_url', models.URLField(max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_metrics', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('investment_round', models.CharField(max_length=100)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(max_length=100)),
                ('source_name', models.CharField(max_length=255)),
                ('source_url', models.URLField(max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investors', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('source_name', models.CharField(max_length=255)),
                ('source_url', models.URLField(max_length=500)),
                ('published_date', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='companies.company')),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('source_name', models.CharField(max_length=255)),
                ('source_url', models.URLField(max_length=500)),
                ('published_date', models.CharField(blank=True, max_length=100)),
                ('accessed_date', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='companies.company')),
            ],
        ),
    ]
